"""
Module for working with foil data.
"""
from __future__ import division, print_function
import pandas as _pd
import numpy as _np

class FoilData(object):
    """
    Object that represents a foil characteristic database.
    """
    def __init__(self):
        self.df = _pd.DataFrame()

    def read(self, fpath, startline=None, endline=None):
        """
        Reads foil data from file. Format is detected automatically, but
        column order is not.
        """
        pass
        self.df["alpha"] = _np.arange(3)
        self.df["cl"] = _np.ones(3)
        self.df["cd"] = _np.zeros(3)

    def write(self, fpath):
        """
        Write foil data to file in OpenFOAM format.
        """
        with open(fpath, "w") as f:
            f.write("// Generated by foamPy\n")
            f.write("// (alpha_deg cl cd)\n" )
            for a, cl, cd in zip(self.df.alpha, self.df.cl, self.df.cd):
                f.write("({} {} {})\n".format(a, cl, cd))


def reformat_foildata(input_path, output_path, startline=None, endline=None):
    """
    Reformats foil data file into a list of 3-element OpenFOAM lists.
    """
    fd = FoilData()
    fd.read(input_path, startline, endline)
    fd.write(output_path)

def test_reformat_foildata():
    """
    Tests the `foampy.foil.reformat_foildata` function.
    """
    ifp = "test/NACA_0021.dat"
    ofp = "test/NACA_0021.txt"
    reformat_foildata(ifp, ofp)
    