#!/usr/bin/env python
"""
This script creates a generic `.gitignore` file in the present directory
"""


if __name__ == "__main__":
    text = """*.gz
log.*
postProcessing
*~
processor*
[0-9]*
[0-9]*.[0-9]*
!0.org
constant/extendedFeatureEdgeMesh
*.eMesh
constant/polyMesh/*
!constant/polyMesh/blockMeshDict
constant/cellToRegion
*.OpenFOAM
"""

    with open(".gitignore", "w") as f:
        f.write(text)
