#!/usr/bin/env python
"""
This script mirrors foil data (in OpenFOAM list format) about zero angle of
attack. Comments will all be written in the header.
"""
from __future__ import division, print_function
import foampy.foil
import argparse


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Mirror foil data about "
                                     "zero degrees angle of attack.")
    parser.add_argument("infile", help="Input file path")
    parser.add_argument("outfile", help="Output file path")
    args = parser.parse_args()
    foampy.foil.mirror_foildata(args.infile, args.outfile)
